version: "3.7"

x-service-volumes: &service-volumes
  - ./:/app/:rw,cached

x-database-variables: &database-variables
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

x-app-variables: &app-variables
  <<: *database-variables
  POSTGRES_HOST: postgres

services:
  website:
    image: vpriya-website:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes: *service-volumes
    depends_on:
      - db_migrate
    ports:
    - "8000:8000"

  db_migrate:
    image: vpriya-website:latest
    volumes: *service-volumes
    command: python manage.py migrate
    environment: *app-variables
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      -"5432:5432"
    environment: *database-variables
    volumes:
    - db-data:/var/lib/postgresql/data

volumes:
  db-data: